name: aipetto
description: Pets and services connected everywhere

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4+28

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  percent_indicator: ^3.4.0
  shared_preferences: ^2.0.12
  flutter_staggered_grid_view: ^0.6.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  image_picker: ^0.8.0+4
  easy_localization: ^3.0.0
  nb_utils: ^4.4.10
  dots_indicator: ^2.0.0
  provider: ^6.0.2
  http: ^0.13.4
  bloc: ^8.0.2
  geolocator: ^8.0.3
  permission_handler: ^8.3.0
  google_maps_flutter: ^2.1.1
  dio: ^4.0.4
  animate_do: ^2.1.0
  flutter_secure_storage: ^5.0.2
  sliding_up_panel: ^2.0.0+1

  flutter_svg: ^1.0.1
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  font_awesome_flutter: ^9.2.0
  google_sign_in: ^5.2.3
  uuid: 3.0.5
  introduction_screen: ^2.1.0
  in_app_update: ^2.0.0
  package_info: ^2.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/credentials.json
    - assets/images/
    - assets/images/pets/
    - assets/images/logos/
    - assets/images/icon/
    - assets/images/aipetto/
    - assets/images/illustrations/
    - assets/images/animations/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/
    - assets/languages/
    - assets/tensor/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

